Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace BuyWise.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }
    }
}

Controllers/CustomerController.cs
using BuyWise.Models;
using Microsoft.AspNetCore.Mvc;

namespace BuyWise.Controllers
{
    public class CustomerController : Controller
    {

        BuyWiseDBContext _dbContext = new();
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(Customer customer)
        {
            _dbContext.Add(customer);
            _dbContext.SaveChanges();

            return RedirectToAction("Login");
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Logout()
        {

            // Check equal false
            if (false)
            {
                return RedirectToAction("Login");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }


    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using BuyWise.Models.Orders;
using BuyWise.Models;

namespace BuyWise.Controllers
{

    public class CardDetail
    {
        public long ProductId { get; set; }
        public int Qty { get; set; } = 1;
        public decimal ProductPrice { get; set; }
        public decimal ProductPriceAfterDiscount { get; set; }
    }
    public class OrderController : Controller
    {

        BuyWiseDBContext _dbContext;
        public OrderController()
        {
            _dbContext = new();
        }

        public IActionResult Index()
        {
            return View();
        }



        public IActionResult AddToCart(CardDetail cardDetail)
        {
            Order order = new()
            {
                Name = "",
                OrderDate = DateTime.Now,
                CustomerId = 2,
                OrderStatusId = 1,
                RefrenceNumber = "123456789",
                 
            };
                _dbContext.Orders.Add(order);


            order.OrderDetails.Add(new OrderDetail()
            {
                OrderId = 0,
                ProductId = cardDetail.ProductId,
                Qty = cardDetail.Qty,
                ItemPrice = cardDetail.ProductPrice,
                ItemPriceAfterDiscount = cardDetail.ProductPriceAfterDiscount,

            });
            

            return View();
        }
    }
}

Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using BuyWise.Models;

namespace BuyWise.Controllers
{
    public class SearchFilterItems
    {
        public string? ProductName { get; set; }
        public decimal? MinimumPrice { get; set; }
        public decimal? MaximumPrice { get; set; }
        public long? CategoryId { get; set; }
        public long? BrandId { get; set; }
        public string? SearchFor { get; set; }
    }

    public class SearchController : Controller
    {
        BuyWiseDBContext _dbContext;
        public SearchController()
        {
            _dbContext = new();
        }
        public IActionResult Index(SearchFilterItems searchFilterItems)
        {

            var result = _dbContext.Products
                    .Where(p =>
                            (searchFilterItems.ProductName == null || p.Name == searchFilterItems.ProductName)
                            &&
                            (
                            (searchFilterItems.MinimumPrice == null || p.CurrentPrice >= searchFilterItems.MinimumPrice)
                            &&
                            (searchFilterItems.MaximumPrice == null || p.CurrentPrice <= searchFilterItems.MaximumPrice)
                            )
                            &&
                            (searchFilterItems.CategoryId == null || p.CategoryId == searchFilterItems.CategoryId)
                            &&
                            (searchFilterItems.BrandId == null || p.BrandId == searchFilterItems.BrandId)
                            &&
                            (searchFilterItems.SearchFor == null
                            || (p.Name + p.Category.Name + p.Brand.Name + p.Description + p.ShortDescription + p.Category.Description).Contains(searchFilterItems.SearchFor))
                    )
                    .Select(p => new
                    {
                        ProductId = p.Id,
                        ProductName = p.Name,
                        ProductShortDescription = p.ShortDescription,
                        ProductPrice = p.CurrentPrice,
                        ProductPriceAfterDiscount = p.CurrentPrice * (decimal)0.65,
                        ProductDescription = p.Description,
                        ProductCategoryId = p.CategoryId,
                        ProductCategoryName = p.Category!.Name,
                        ProductBrandId = p.BrandId,
                        ProductBrand = p.Brand!.Name,
                        ProductImage = p.ProductImages!.FirstOrDefault(i => i.IsDefault == true)!.ImageUrl,
                    }
                ).OrderByDescending(p => p.ProductId).ToList();


            return View(result);
        }
    }
}

Views/Shared/Partials/_CategoriesList.cshtml
<nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 1000;">
    <div class="navbar-nav w-100 overflow-hidden" style="height: 215px;">
        <a asp-controller="Search" asp-action="Index" asp-route-categoryId="1" class="nav-item nav-link">Top 10 Offers</a>
        <a asp-controller="Search" asp-action="Index" asp-route-categoryId="2" class="nav-item nav-link">Electronics & Digital</a>
        <a asp-controller="Search" asp-action="Index" asp-route-categoryId="3" class="nav-item nav-link">Phones & Tablets</a>
        <a asp-controller="Search" asp-action="Index" asp-route-categoryId="4" class="nav-item nav-link">Televisions & Monitors</a>
        <a asp-controller="Search" asp-action="Index" asp-route-categoryId="5" class="nav-item nav-link">Jewelry & Watches</a>
    </div>
</nav>

Views/Shared/Partials/_Footer.cshtml
<!-- Footer Start -->
<div class="container-fluid footer-bg text-dark mt-5 pt-5">
    <div class="row px-xl-5 pt-5">
        <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
            <a href="/" class="text-decoration-none d-flex align-items-center mb-4">
                <span class="logo-icon mr-2">
                    <i class="fas fa-shopping-bag"></i>
                </span>
                <span class="logo-text display-5 font-weight-semi-bold">
                    <span class="buy">Buy</span><span class="wise">Wise</span>
                </span>
            </a>
            <p>
                <strong>BuyWise</strong> makes shopping smart and simple. Discover quality, affordability, and
                convenience all in one place. Shop wise, live better!
            </p>


            <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>642 Street, Giza, Egypt</p>
            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>ehab.sadiq89@gmail.com</p>
            <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+20 103 381 3411</p>
        </div>
        <div class="col-lg-8 col-md-12">
            <div class="row">
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-light mb-4">Find It Fast</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-dark mb-2" href="index.html">
                            <i class="fa fa-angle-right mr-2"></i>Laptops &
                            Computers
                        </a>
                        <a class="text-dark mb-2" href="shop.html">
                            <i class="fa fa-angle-right mr-2"></i>Smart Phones &
                            Tablets
                        </a>
                        <a class="text-dark mb-2" href="detail.html">
                            <i class="fa fa-angle-right mr-2"></i>
                            TV & Audio
                        </a>
                        <a class="text-dark mb-2" href="cart.html">
                            <i class="fa fa-angle-right mr-2"></i>Appliances
                        </a>
                        <a class="text-dark mb-2" href="checkout.html">
                            <i class="fa fa-angle-right mr-2"></i>Jewelry & Watches
                        </a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-light mb-4">Services</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-dark mb-2" href="index.html">
                            <i class="fa fa-angle-right mr-2"></i>Support
                            Center
                        </a>
                        <a class="text-dark mb-2" href="shop.html">
                            <i class="fa fa-angle-right mr-2"></i>Terms &
                            Conditions
                        </a>
                        <a class="text-dark mb-2" href="detail.html">
                            <i class="fa fa-angle-right mr-2"></i>Privacy
                            Policy
                        </a>
                        <a class="text-dark mb-2" href="cart.html">
                            <i class="fa fa-angle-right mr-2"></i>Help
                            Cart
                        </a>
                        <a class="text-dark mb-2" href="checkout.html">
                            <i class="fa fa-angle-right mr-2"></i>FAQS
                        </a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-light mb-4">BuyWise's Newsletter</h5>
                    <form action="">
                        <div class="form-group">
                            <input type="text" class="form-control border-0 py-4" placeholder="Your Name"
                                   required="required" />
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control border-0 py-4" placeholder="Your Email"
                                   required="required" />
                        </div>
                        <div>
                            <button class="btn btn-primary btn-block border-0 py-3" type="submit">Subscribe Now</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row border-top border-light mx-xl-5 py-4">
        <div class="col-md-6 px-xl-0">
            <p class="mb-md-0 text-center text-md-left text-dark">
                &copy; <a class="text-dark font-weight-semi-bold" href="@Url.Action("Index", "Home")">BuyWise</a>. All
                Rights Reserved.
            </p>
        </div>
        <div class="col-md-6 px-xl-0 text-center text-md-right">
            <img class="img-fluid" src="img/payments.png" alt="">
        </div>
    </div>
</div>
<!-- Footer End -->
<!-- Back to Top -->
<a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>


<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/easing/easing.min.js"></script>
<script src="~/lib/owlcarousel/owl.carousel.min.js"></script>

<!-- Contact Javascript File -->
<script src="~/mail/jqBootstrapValidation.min.js"></script>
<script src="~/mail/contact.js"></script>

<!-- Template Javascript -->
<script src="~/js/main.js"></script>

<script>
    $(document).ready(function () {
        $(".addtocardbtn").click(function () {

            var productId = $(this).data("id");
            var productPrice = $(this).data("price");
            var productPriceAfterDiscount = $(this).data("priceafterdiscount");

            const data = { productId: productId, productPrice: productPrice, productPriceAfterDiscount: productPriceAfterDiscount };

            $.ajax({
                url: '@Url.Action("AddToCart", "Order")',//  '/Order/AddToCard',
                type: 'POST',
                contentType: 'application/json; charset=utf-8',
                data: JSON.stringify(data),
                success: function (data) {
                    alert(data);
                }
            })
        })

    });
</script>

Views/Shared/Partials/_Head.cshtml
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BuyWise</title>

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">
</head>

Views/Shared/Partials/_NavBar.cshtml
@{
    var currentController = ViewContext.RouteData.Values["controller"]?.ToString();
    var currentAction = ViewContext.RouteData.Values["action"]?.ToString();
}

<!-- Navbar Start -->
<div class="container-fluid">
    <div class="row border-top px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                <h6 class="m-0">Categories</h6>
                <i class="fa fa-angle-down text-dark"></i>
            </a>
            <partial name="_CategoriesList.cshtml" />
        </div>
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">E</span>Shopper</h1>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <a href="@Url.Action("Index", "Home")" class="nav-item nav-link @(currentController == "Home" && currentAction == "Index" ? "active" : "")">Home</a>
                        <a href="@Url.Action("Index", "Shop")" class="nav-item nav-link @(currentController == "Home" && currentAction == "Shop" ? "active" : "")">Shop</a>
                        <a href="@Url.Action("Index", "About")" class="nav-item nav-link @(currentController == "Home" && currentAction == "About" ? "active" : "")">About</a>
                        <a href="@Url.Action("Contact", "About")" class="nav-item nav-link @(currentController == "Home" && currentAction == "Contact" ? "active" : "")">Contact</a>
                    </div>
                    <div class="navbar-nav ml-auto py-0">
                        <a href="@Url.Action("Login", "Customer")" class="nav-item nav-link">Login</a>
                        <a href="@Url.Action("Register", "Customer")" class="nav-item nav-link">Register</a>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>
<!-- Navbar End -->

Views/Shared/Partials/_TopBar.cshtml
<!-- Topbar Start -->
<div class="container-fluid">
    <div class="row bg-secondary py-2 px-xl-5">
        <div class="col-lg-6 d-none d-lg-block">
            <div class="d-inline-flex align-items-center">
                <a class="text-dark" href="">FAQs</a>
                <span class="text-muted px-2">|</span>
                <a class="text-dark" href="">Help</a>
                <span class="text-muted px-2">|</span>
                <a class="text-dark" href="">Support</a>
            </div>
        </div>
        <div class="col-lg-6 text-center text-lg-right">
            <div class="d-inline-flex align-items-center">
                <a class="text-dark px-2" href="">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a class="text-dark px-2" href="">
                    <i class="fab fa-twitter"></i>
                </a>
                <a class="text-dark px-2" href="">
                    <i class="fab fa-linkedin-in"></i>
                </a>
                <a class="text-dark px-2" href="">
                    <i class="fab fa-instagram"></i>
                </a>
                <a class="text-dark pl-2" href="">
                    <i class="fab fa-youtube"></i>
                </a>
            </div>
        </div>
    </div>
    <div class="row align-items-center py-3 px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a href="/" class="text-decoration-none d-flex align-items-center">
                <span class="logo-icon mr-2">
                    <i class="fas fa-shopping-bag"></i>
                </span>
                <span class="logo-text">
                    <span class="buy">Buy</span><span class="wise">Wise</span>
                </span>
            </a>
        </div>
        <div class="col-lg-6 col-6 text-left">
            <form asp-controller="Search" asp-action="Index" method="post">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for products" name="searchFor">
                    <div class="input-group-append">
                        <button class="input-group-text bg-transparent text-primary" type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                        <button class="input-group-text bg-transparent p-2" type="button" data-toggle="modal"
                                data-target="#advancedSearchModal" title="Advanced Search" style="border-left: none;">
                            <i class="fas fa-filter" style="font-size: 1.1rem; color: #FF8716;"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-3 col-6 text-right">
            <a href="" class="btn border">
                <i class="fas fa-heart text-primary"></i>
                <span class="badge">0</span>
            </a>
            <a href="" class="btn border">
                <i class="fas fa-shopping-cart text-primary"></i>
                <span class="badge">0</span>
            </a>
        </div>
    </div>
</div>
<!-- Topbar End -->
<!-- Modal -->
<div class="modal fade" id="advancedSearchModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-md" role="document">
        <div class="modal-content">
            <form method="post" asp-action="index" asp-controller="search">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Advanced Search</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <div class="form-group">
                        <label for="ProductName">Product Name</label>
                        <input type="text" class="form-control" id="ProductName" name="ProductName"
                               placeholder="Enter Product Name" autofocus>
                    </div>
                    <div class="form-group">
                        <label for="MinimumPrice" style="display:block;">Product Price</label>
                        <input type="number" class="form-control" style="display:inline-block;width:45%"
                               id="MinimumPrice" name="MinimumPrice" placeholder="Minimum Price">
                        <span> - </span>
                        <input type="number" class="form-control" style="display:inline-block;width:45%"
                               id="MaximumPrice" name="MaximumPrice" placeholder="Maximum Price">
                    </div>
                    <div class="form-group">
                        <label for="CategoryId">Category</label>
                        <select class="form-control" id="CategoryId" name="CategoryId">
                            <option>Select Category</option>
                            <option value="2">Electornics & Digital </option>
                            <option value="3">Smarth Phones & Tablets</option>
                            <option value="4">Swimwear</option>
                            <option value="5">Sleepwear</option>
                            <option value="6">Jumpsuits</option>
                            <option value="7">Jackets</option>
                            <option value="8">Shoes</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="BrandId">Brand</label>
                        <select class="form-control" id="BrandId" name="BrandId">
                            <option>Select Brand</option>
                            <option value="1">Brand - 1</option>
                            <option value="2">Brand - 2</option>
                            <option value="3">Brand - 3</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="SearchFor">Search For</label>
                        <textarea class="form-control" id="SearchFor" name="SearchFor" rows="3"></textarea>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary"><span class="fas fa-search"></span> Search</button>
                </div>
            </form>
        </div>
    </div>
</div>